version: '3.4'

services:
  app:
    image: jfahrer/todomvc:latest
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      - PG_USERNAME=postgres
      - PG_PASSWORD=secret
      - PG_HOST=pg
      - PG_PORT=5432

  pg:
    image: postgres:9.6-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - PG_USERNAME=postgres
      - PG_PASSWORD=secret

volumes:
  pg-data:
